#!/usr/bin/env node

/**
 * Builds dist/pwa/ from src/.
 *
 * Everything in src/ ships except the build inputs, so adding a widget needs
 * no change here. The service worker's precache list is generated from the
 * result rather than maintained by hand.
 */

const fs = require('fs');
const path = require('path');
const { copyTree, listFiles, readVersion } = require('./lib');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'src');
const OUT = path.join(ROOT, 'dist', 'pwa');

const EXCLUDE = new Set(['input.css']);

const PRECACHE_SKIP = new Set(['sw.js', 'LICENSE']);

// The shell is code and markup, whatever its size, plus small assets. Bulk
// content is fetched and cached on first use instead: the backdrop library
// alone is ~13MB, and precaching it would download the lot on install.
const SHELL_TYPES = ['.html', '.css', '.js', '.webmanifest'];
const MAX_ASSET_BYTES = 64 * 1024;

function isShell(file) {
  if (PRECACHE_SKIP.has(file)) return false;
  if (SHELL_TYPES.includes(path.extname(file))) return true;
  return fs.statSync(path.join(OUT, file)).size <= MAX_ASSET_BYTES;
}

// Anchored after the viewport meta so the charset declaration stays first.
const HEAD_ANCHOR = '<meta name="viewport" content="width=device-width, initial-scale=1.0">';

const PWA_HEAD = `${HEAD_ANCHOR}
  <link rel="manifest" href="manifest.webmanifest">
  <meta name="theme-color" content="#3b82f6">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta name="apple-mobile-web-app-title" content="StartBoard">
  <link rel="apple-touch-icon" href="img/icon-192.png">
  <script src="version.js"></script>`;

const SW_REGISTRATION = `  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', () => {
        navigator.serviceWorker.register('./sw.js')
          .catch((error) => console.warn('ServiceWorker registration failed:', error));
      });
    }
  </script>
</body>`;

function patch(file, replacements) {
  const target = path.join(OUT, file);
  let text = fs.readFileSync(target, 'utf-8');
  for (const [token, value] of Object.entries(replacements)) {
    if (!text.includes(token)) throw new Error(`${file}: expected to find ${token}`);
    text = text.replaceAll(token, value);
  }
  fs.writeFileSync(target, text);
}

function build() {
  const version = readVersion(ROOT);
  console.log(`Building PWA (v${version})...`);

  fs.rmSync(OUT, { recursive: true, force: true });
  copyTree(SRC, OUT, EXCLUDE);
  fs.copyFileSync(path.join(ROOT, 'LICENSE'), path.join(OUT, 'LICENSE'));

  fs.writeFileSync(
    path.join(OUT, 'version.js'),
    `// Generated by scripts/build-pwa.js\nwindow.STARTBOARD_VERSION = '${version}';\n`,
  );

  patch('index.html', { [HEAD_ANCHOR]: PWA_HEAD, '</body>': SW_REGISTRATION });

  const shell = listFiles(OUT).filter(isShell);
  const precache = ['./', ...shell.map((file) => `./${file}`)];

  patch('sw.js', { '{{VERSION}}': version, '{{ASSETS}}': JSON.stringify(precache, null, 2) });

  const bytes = shell.reduce((total, file) => total + fs.statSync(path.join(OUT, file)).size, 0);
  console.log(`  ${precache.length} files precached (${Math.round(bytes / 1024)}KB)`);
  console.log('  Output: dist/pwa/  (test with: npx serve dist/pwa)');
}

build();
